version: '3'

services:
  host-a:
    privileged: true
    # environment:
    #   - TARGET=10.0.15.0/24
    #   - GW=10.0.10.4
    build: .
    networks:
      host-a-r1:
        ipv4_address: 10.0.10.3
  r1:
    privileged: true
    environment:
      - IPS=10.0.10.4:10.0.11.3:10.0.12.3
    build: .
    networks:
      host-a-r1:
        ipv4_address: 10.0.10.4
      r1-r2:
        ipv4_address: 10.0.11.3
      r1-r4:
        ipv4_address: 10.0.12.3
  r2:
    privileged: true
    environment:
      - IPS=10.0.11.4:10.0.13.3
    build: .
    networks: 
      r1-r2:
        ipv4_address: 10.0.11.4
      r2-r3:
        ipv4_address: 10.0.13.3
  r3:
    privileged: true
    environment:
      - IPS=10.0.13.4:10.0.14.4:10.0.15.3
    build: .
    networks:
      r2-r3:
        ipv4_address: 10.0.13.4
      r4-r3:
        ipv4_address: 10.0.14.4
      r3-host-b:
        ipv4_address: 10.0.15.3
  r4:
    privileged: true
    profiles: ["r4"]
    environment:
      - IPS=10.0.12.4:10.0.14.3
    build: .
    networks:
      r1-r4:
        ipv4_address: 10.0.12.4
      r4-r3:
        ipv4_address: 10.0.14.3
  host-b:
    privileged: true
    # environment:
    #   - TARGET=10.0.10.0/24
    #   - GW=10.0.15.3
    build: .
    networks:
      r3-host-b:
       ipv4_address: 10.0.15.4

networks:
  host-a-r1:
    ipam:
      config:
        - subnet: 10.0.10.0/24
  r1-r2:
    ipam:
      config:
        - subnet: 10.0.11.0/24
  r1-r4:
    ipam:
      config:
        - subnet: 10.0.12.0/24
  r2-r3:
    ipam:
      config:
        - subnet: 10.0.13.0/24
  r4-r3:
    ipam:
      config:
        - subnet: 10.0.14.0/24
  r3-host-b:
    ipam:
      config:
        - subnet: 10.0.15.0/24